#!/bin/busybox sh

mount -a                       # Mount all mounts listed in /etc/fstab
/sbin/mdev -s                  # Populate /dev
/bin/hostname -F /etc/hostname # Set hostname
/sbin/ifconfig lo 127.0.0.1 up # Initialize loopback

